### ISSUE TITLE
error code 2306-0103

### ISSUE THREAD

**Issue by ffsaga** [kinnay/SMB35#15]
Does not happen with 2 players
When 3 players,
At the beginning of the game,
Player A runs to commit suicide
show error
```
WARNING:nintendo.nex.matchmaking_eagle:MatchmakeRefereeServer.end_round_with_partial_report not implemented
WARNING:nintendo.nex.rmc:RMC failed: Core::NotImplemented (0x80010002)
ERROR:nintendo.nex.prudp:Packet timed out: <PRUDPPacket type=TYPE_DATA flags=NEED_ACK,RELIABLE,HAS_SIZE seq=36 frag=0>
INFO:nintendo.nex.rmc:Connection was closed
INFO:nintendo.nex.notification:NotificationClient.process_notification_event()
INFO:nintendo.nex.messaging:MessageDeliveryServer.deliver_message()
INFO:nintendo.nex.messaging:MessageDeliveryClient.deliver_message()
INFO:nintendo.nex.messaging:MessageDeliveryClient.deliver_message()
```

when B and C wait in place until the time is up:
show error:
```
ERROR:anynet.util:An exception occurred
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\anyio\streams\memory.py", line 79, in receive
    return self.receive_nowait()
  File "C:\Python38\lib\site-packages\anyio\streams\memory.py", line 74, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\anynet\util.py", line 86, in catch
    yield
  File "F:\SMB35\source\eagle.py", line 293, in handle
    await client.process()
  File "F:\SMB35\source\eagle.py", line 84, in process
    data = await self.client.recv()
  File "C:\Python38\lib\site-packages\anynet\websocket.py", line 275, in recv
    return await self.binary_packets.get()
  File "C:\Python38\lib\site-packages\anynet\queue.py", line 18, in get
    return await self.stream.receive()
  File "C:\Python38\lib\site-packages\anyio\streams\stapled.py", line 61, in receive
    return await self.receive_stream.receive()
  File "C:\Python38\lib\site-packages\anyio\streams\memory.py", line 99, in receive
    raise EndOfStream
anyio.EndOfStream
INFO:nintendo.nex.matchmaking_eagle:MatchmakeRefereeServer.end_round()
INFO:nintendo.nex.matchmaking_eagle:MatchmakeRefereeServer.end_round()
INFO:nintendo.nex.matchmaking_eagle:MatchMakingServerExt.end_participation()
INFO:nintendo.nex.notification:NotificationClient.process_notification_event()
INFO:nintendo.nex.matchmaking_eagle:MatchMakingServerExt.end_participation()
INFO:anynet.websocket:WS server is closed
INFO:nintendo.nex.messaging:MessageDeliveryServer.deliver_message()
WARNING:nintendo.nex.rmc:RMC failed: RendezVous::SessionVoid (0x80030073)
```

**Comment by just-another-random-person** [comment]
Same as issue #4 (I also posted the fix there)

**Comment by ffsaga** [comment]
patch works, thank you.
